---
title: "Correlation"
author: "Oren Ross"
date: "7/29/2020"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Correlation Testing

```{r Correlation Testing}

# Loop to create chart of corrrelation between SQS and NYSA (mean)
LoopFinalDF = data.frame(matrix(vector(), 1, 5))
colnames(LoopFinalDF) <- c(paste("SQS"), paste("ELA p-value"), paste("ELA r"), paste("Math p-value"), paste("Math r"))
for (i in 6:10){
  loopDF = data.frame(matrix(vector(), 1, 5))
loop1ctest <- cor.test(FinalDF[,i], FinalDF[,11], method="pearson")
loop2ctest <- cor.test(FinalDF[,i], FinalDF[,29], method="pearson")
loopDF[1,1] <- colnames(FinalDF[i])
loopDF[1,2] <- loop1ctest$p.value
loopDF[1,3] <- loop1ctest$estimate
loopDF[1,4] <- loop2ctest$p.value
loopDF[1,5] <- loop2ctest$estimate
colnames(loopDF) <- c(paste("SQS"), paste("ELA p-value"), paste("ELA r"), paste("Math p-value"), paste("Math r"))
   LoopFinalDF <- bind_rows(LoopFinalDF , loopDF) 
}
NYSA_SQS_corrchart <-    LoopFinalDF[-1,]

 # Creating visual of correlations between multiple stats 

# Just SQS
correlationStats <- FinalDF[c(6:10)]


correlationStats <- FinalDF[c(8,11)]
correlationStats <- FinalDF[c(8,29)]
correlationStats <- FinalDF[c(6:10)]
# chart.Correlation(correlationStats, method="pearson")
# Creating correlation and p-value data frames
corr <- cor(correlationStats, method = "pearson")
p.mat <- cor_pmat(correlationStats, method = "pearson")

# Plotting the correlations
ggcorrplot(corr,
           type = "upper",
           lab = TRUE,
           lab_size = 4,
           p.mat = p.mat,
  insig = "blank",
  digits = 2, 
  sig.level = .001)


# SQS to Scores
correlationStats <- FinalDF[c(6:10, 11, 29)]
# Creating correlation and p-value data frames
corr <- cor(correlationStats, method = "pearson")
p.mat <- cor_pmat(correlationStats, method = "pearson")

# Plotting the correlations

ggcorrplot(corr,
           type = "upper",
           lab = TRUE,
           lab_size = 3,
           p.mat = p.mat,
  insig = "blank",
  digits = 2, 
  sig.level = .001)


# Scores
correlationStats <- FinalDF[c(11, 17, 23, 29, 35, 41)]
# Creating correlation and p-value data frames
corr <- cor(correlationStats, method = "pearson", use = "complete.obs")
p.mat <- cor_pmat(correlationStats, method = "pearson")
pairs.panels(FinalDF[c(11, 17, 23, 29, 35, 41)])
# Plotting the correlations

ggcorrplot(corr,
           type = "upper",
           lab = TRUE,
           lab_size = 3,
           p.mat = p.mat,
  insig = "blank",
  digits = 2, 
  sig.level = .001)


# SQS to Demographics (half)
correlationStats <- FinalDF[c(6:10, 50:54)]
# Creating correlation and p-value data frames
corr <- cor(correlationStats, method = "pearson")
p.mat <- cor_pmat(correlationStats, method = "pearson")

# Plotting the correlations
ggcorrplot(corr,
           type = "upper",
           lab = TRUE,
           lab_size = 3,
           p.mat = p.mat,
  insig = "blank",
  digits = 2, 
  sig.level = .001)


# SQS to Demographics (other half)
correlationStats <- FinalDF[c(6:10, 55:58)]
# Creating correlation and p-value data frames
corr <- cor(na.omit(correlationStats), method = "pearson")
p.mat <- cor_pmat(na.omit(correlationStats), method = "pearson")



# Plotting the correlations
ggcorrplot(corr,
           type = "upper",
           lab = TRUE,
           lab_size = 3,
           p.mat = p.mat,
  insig = "blank",
  digits = 2, 
  sig.level = .001)



# Scores to Demographics (half)
correlationStats <- FinalDF[c(11, 29, 50:54)]
# Creating correlation and p-value data frames
corr <- cor(correlationStats, method = "pearson")
p.mat <- cor_pmat(correlationStats, method = "pearson")

# Plotting the correlations
ggcorrplot(corr,
           type = "upper",
           lab = TRUE,
           lab_size = 3,
           p.mat = p.mat,
  insig = "blank",
  digits = 2, 
  sig.level = .001)



# Scores to Demographics (other half)
correlationStats <- FinalDF[c(11, 29, 55:58)]
# Creating correlation and p-value data frames
corr <- cor(correlationStats, method = "pearson")
p.mat <- cor_pmat(correlationStats, method = "pearson")

# Plotting the correlations
ggcorrplot(corr,
           type = "upper",
           lab = TRUE,
           lab_size = 3,
           p.mat = p.mat,
  insig = "blank",
  digits = 2, 
  sig.level = .001)



# Just Demographics
correlationStats <- FinalDF[c(50:58)]
# Creating correlation and p-value data frames
corr <- cor(correlationStats, method = "pearson")
p.mat <- cor_pmat(correlationStats, method = "pearson")

# Plotting the correlations
ggcorrplot(corr,
           type = "upper",
           lab = TRUE,
           lab_size = 3,
           p.mat = p.mat,
  insig = "blank",
  digits = 2, 
  sig.level = .001)





LoopFinalDF = data.frame(matrix(vector(), 1, 5))
colnames(LoopFinalDF) <- c(paste("Demographic"), paste("ELA p-value"), paste("ELA r"), paste("Math p-value"), paste("Math r"))
for (i in 50:58){
  loopDF = data.frame(matrix(vector(), 1, 5))
loop1ctest <- cor.test(FinalDF[,i], FinalDF[,11], method="pearson")
loop2ctest <- cor.test(FinalDF[,i], FinalDF[,29], method="pearson")
loopDF[1,1] <- colnames(FinalDF[i])
loopDF[1,2] <- loop1ctest$p.value
loopDF[1,3] <- loop1ctest$estimate
loopDF[1,4] <- loop2ctest$p.value
loopDF[1,5] <- loop2ctest$estimate
colnames(loopDF) <- c(paste("Demographic"), paste("ELA p-value"), paste("ELA r"), paste("Math p-value"), paste("Math r"))
   LoopFinalDF <- bind_rows(LoopFinalDF , loopDF) 
}
NYSA_Demo_corrchart <-    LoopFinalDF[-1,]


```


```{r APA correlation tables}

apa.cor.table(FinalDF[,c(6:10)], filename = "CorTable_SQS.doc")
apa.cor.table(FinalDF[,c(11, 17, 23, 29, 35, 41)], filename = "CorTable_NYSA.doc")
apa.cor.table(FinalDF[,c(50:58)], filename = "CorTable_Demo.doc")

apa.cor.table(FinalDF[,c(6:10, 11, 29)], filename = "CorTable_SQS_NYSA.doc")

apa.cor.table(FinalDF[,c(6:10, 50:54)], filename = "CorTable_SQS_Demo.doc")
apa.cor.table(FinalDF[,c(6:10, 55:58)], filename = "CorTable_SQS_Demo.doc")

apa.cor.table(FinalDF[,c(11, 29, 50:54)], filename = "CorTable_NYSA_Demo.doc")
apa.cor.table(FinalDF[,c(11, 29, 55:58)], filename = "CorTable_NYSA_Demo.doc")

```

